let testData = [{
    name: "Invictus-",
    word: "今天天气很好!",
    url: require('../../img/MePage/me.png'),
    date: '2小时前',
    address: '上海',
    showHeart: false,
    photo: [require('../../img/test/Test1.png'),
        require('../../img/test/Test2.png'),
        require('../../img/test/Test3.png'),
        require('../../img/test/Test4.png'),
        require('../../img/test/Test5.png'),
        require('../../img/test/Test6.png'),
        require('../../img/test/Test7.png'),
        require('../../img/test/Test1.png'),
        require('../../img/MePage/me.png')],
    comment: [{name:'Invictus-',content:'会换行啦哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈'},
              {name:'马云',content:['我不喜欢钱!']}],
    star: [123,456],
    isStar: false
},
    {
        name: "345",
        word: "345",
        url: require('../../img/MePage/me.png'),
        date: '1小时前',
        address: '1231312',
        showHeart: false,
        photo: [require('../../img/test/Test1.png'),
            require('../../img/test/Test2.png'),
            require('../../img/test/Test3.png'),
            require('../../img/test/Test4.png'),
            require('../../img/test/Test5.png'),
            require('../../img/test/Test6.png'),
            require('../../img/test/Test7.png'),
            require('../../img/test/Test1.png'),
            require('../../img/MePage/me.png')],
        comment: [],
        star: [123],
        isStar: false
    }];

export default testData
